### ISSUE TITLE
NavMesh and custom nodes/tracks

### ISSUE THREAD

**Issue by Linertank** [Sage-of-Mirrors/NaviGator#1]
Hello, I'd like to ask you a few questions about using the navigator, great job already, bravo and thank you for your work! So I've actually seen that you've planned a fix for loading navmesh which with the new version crashes the software, but we agree that it's the navlesh with the numbers between [] that should be loaded?

Then, concerning nodes, you explain that you can create tracks by right-clicking in the list on the left, so it works, I can create the file, but how do you create new nodes linked to the new track? How can I make a selected node independent? I confess I don't understand the whole process in the viewport :)

Thanks a lot :)

**Comment by Linertank** [comment]
I found for the custom nodes with the new track but I just made a loop test and inserted in redM following the explanation but the game crashes when entering the server here is the error: "an exception occured (c0000005 at 0x7ff71113d061) during loading of resources:/RAILSTRACK/data/traintracks.xml in data file mounter 0x143471860"

**Comment by Sage-of-Mirrors** [comment]
Hey, I was just about to respond. Looks like I missed a step for the RedM instructions - you need to make the filepaths to the new *.dat files in your` traintracks.xml` relative to your resource. So if you *.dat files are at `RAILSTRACK/data/*.dat`, you need to change the path in traintracks.xml to `resources:/RAILSTRACK/data/*.dat`.

> but we agree that it's the navlesh with the numbers between [] that should be loaded?

Yes, but any navmesh should load. I am working on deprecating navmesh visualization in favor of rendering the world map as it should be, but that won't be ready for a while.

Thanks for using NaviGator! Let me know if you have any more questions or suggestions.

**Comment by Linertank** [comment]
Like this so ? 

<?xml version="1.0"?>
<train_tracks
	version="1">
	<train_track
		filename="resources:/RAILSTRACK/data/trains_elizabeth.dat"
		trainConfigName="trains_elizabeth"
		stopsAtStations="false"
		brakingDist="10" />
</train_tracks>

:) it's a pleasure !

**Comment by Sage-of-Mirrors** [comment]
Yes, that should be correct.

**Comment by Linertank** [comment]
And so, if I've understood correctly, you can't add a junction with existing rails? And for the addition of custom rails, you agree to implement only new rails? Like when you add meta ped, basically.

**Comment by Linertank** [comment]
Thanks in any case for your quick and efficient answers, I'll let you pull your hair out with the navmesh and I'll try to figure out the rails and guess the path blindly xD, I'll test and get back to you to tell you if everything is good. ;)

**Comment by Sage-of-Mirrors** [comment]
> And so, if I've understood correctly, you can't add a junction with existing rails? And for the addition of custom rails, you agree to implement only new rails? Like when you add meta ped, basically.

Correct, you cannot connect custom tracks to existing tracks with RedM as it currently is. I tried to contribute to CFX to fix that, but my change was rejected. Might be able to propose another fix later, but we'll see.

> Thanks in any case for your quick and efficient answers, I'll let you pull your hair out with the navmesh and I'll try to figure out the rails and guess the path blindly xD, I'll test and get back to you to tell you if everything is good. ;)

No problem! Currently unemployed so I have nothing better to do x)

**Comment by Linertank** [comment]
It's working perfectly, when i finish my track i'll send to you, thanks man !!

**Comment by Linertank** [comment]
Thank you for your work, I've just finished the rails between EAST and WEST, I'll let you see the part of the video at 16min31. It's all thanks to you too ;)

https://www.youtube.com/watch?v=hugdhBp2mIw
